
server:
  port: 8081

logging:
  level:
    org.springframework.security: trace

algafood:
  jwt:
    keystore:
      path: keystores/oauth2.jks
      password: 123456
      keypair-alias: oauth2

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/algafood?useSSL=false&serverTimezone=UTC
    username: root
    password: admin
